### ISSUE TITLE
能否为每个账号配置独立的cron

### ISSUE THREAD

**Issue by fanyouzhao** [sjkhsl/study_xxqg#13]
作者你好，多个账户时，能否为每个账号配置独立的cron，服务器内存较小时，同时运行多个账号学习会造成资源紧张

**Comment by cosir888** [comment]
并非同时运行，据我观察是顺序执行。

**Comment by fanyouzhao** [comment]
> 并非同时运行，据我观察是顺序执行。

查看了一下积分明细，发现确实是顺序执行。多谢回复！
