### ISSUE TITLE
突然用不了了

### ISSUE THREAD

**Issue by ggbond11** [sjkhsl/study_xxqg#15]
![图片](https://user-images.githubusercontent.com/49777663/213962023-36d4bdaa-e51c-473c-be4d-423a22f826af.png)

**Comment by lyljj001** [comment]
仅仅图中这个报错只是学习的题库文件下载失败，要下载是1.0.37旧版的，你可以手动去最新版本1.0.39下载源码Source code
(zip)里找到这个同名文件放到学习主程序目录下即可

**Comment by mike7575** [comment]
端口二维码怎么扫啊，提示我在手机上完成。。。。。。。。
