### ISSUE TITLE
不能获取当日得分与总分，请教如何处理

### ISSUE THREAD

**Issue by adamnb1** [sjkhsl/study_xxqg#18]
![image](https://user-images.githubusercontent.com/59300677/221089487-a17469b9-875e-46e3-b948-6d40511dabcf.png)

**Comment by adamnb1** [comment]
![image](https://user-images.githubusercontent.com/59300677/221089550-e2021d8b-412b-49ea-8557-d1c2d80ac39a.png)

**Comment by wood-code** [comment]
需要修改lib/url.go里面的请求地址，有人提PR了，作者没合并

**Comment by xlh001** [comment]
已修复，请更新
