### ISSUE TITLE
关于ipv6的问题

### ISSUE THREAD

**Issue by bzlzm** [sjkhsl/study_xxqg#19]
前天刚在群晖docker里部署完，成功运行的第三天，感谢大佬！
唯一不足的是怎么开启ipv6的地址或域名访问？

尝试在
----------------------------------
web:

  enable: true

  host: 0.0.0.0
  port: 8888

--------------------------------
  host: 0.0.0.0, [::]  不管用啊，
也试过另起一行再加host不怎么这个语法怎么弄

**Comment by ghwmx** [comment]
我也是公网ipv6，群晖，用ddnsgo做动态解析，然后用群晖的反向代理就可以用域名加端口号访问了
