### ISSUE TITLE
今天突然不能学习了

### ISSUE THREAD

**Issue by qingfeng2288** [sjkhsl/study_xxqg#21]
今天突然不能学习了，日志总是这样
[GIN] 2023/03/21 - 16:32:42 | 200 |  132.759214ms |  111.17.199.245 | GET      "/user"
[2023-03-21 16:32:42] [erro] 文章学习模块异常结束
[2023-03-21 16:32:42] [erro] runtime error: index out of range [0] with length 0
[2023-03-21 16:32:42] [erro] 视频学习模块异常结束
[2023-03-21 16:32:42] [erro] runtime error: index out of range [0] with length 0
[2023-03-21 16:32:42] [erro] 答题模块异常结束或答题已完成
[2023-03-21 16:32:42] [erro] runtime error: index out of range [0] with length 0
[2023-03-21 16:32:43] [erro] 答题模块异常结束或答题已完成
[2023-03-21 16:32:43] [erro] runtime error: index out of range [0] with length 0
[2023-03-21 16:32:43] [erro] 答题模块异常结束或答题已完成
[2023-03-21 16:32:43] [erro] runtime error: index out of range [0] with length 0

**Comment by zengping0219** [comment]
一样 一直没找到解决的办法 有大佬帮下忙吗？

**Comment by varequan** [comment]
接口改了，需要修复

**Comment by zengping0219** [comment]
什么时候能修复好

**Comment by chen714867833** [comment]
最近也发现学不动了，尬住

**Comment by opojin** [comment]
一样，这下鸡了

**Comment by adamnb1** [comment]
学不了了。麻烦作者出来修复一下吧。谢谢

**Comment by adamnb1** [comment]
坐等作者更新，哈哈。

**Comment by shenhui0929** [comment]
坐等作者修复

**Comment by luckywangxi** [comment]
[xlh001](https://github.com/xlh001)
/
[study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用

**Comment by shallbytwo** [comment]
> [xlh001](https://github.com/xlh001) / [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用

也不行

**Comment by Silentely** [comment]
> > [xlh001](https://github.com/xlh001) / [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用
> 
> 也不行

我换这个,可以用

**Comment by Juxdun** [comment]
> 

我换这个,可以用

**Comment by Juxdun** [comment]
> > > [xlh001](https://github.com/xlh001) / [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用
> > 
> > 
> > 也不行
> 
> 我换这个,可以用

我也换这个的docker版,可以用

**Comment by Esingpawn** [comment]
> [xlh001](https://github.com/xlh001)
> /
> [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用

你用这个可以每天自动开始么 设置了定时任务好像不自动开始 需要我手动开始学习

**Comment by Juxdun** [comment]
> > [xlh001](https://github.com/xlh001)
> > /
> > [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用
> 
> 你用这个可以每天自动开始么 设置了定时任务好像不自动开始 需要我手动开始学习

我用的可以7点自动开始

**Comment by 3828669** [comment]
> [xlh001](https://github.com/xlh001) / [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用

可以正常使用，感谢

**Comment by TSL-Johnson** [comment]
> > > > [xlh001](https://github.com/xlh001) / [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用
> > > 
> > > 
> > > 也不行
> > 
> > 
> > 我换这个,可以用
> 
> 我也换这个的docker版,可以用
您好，我也很需要这个的docker镜像，麻烦可以讲讲吗?

**Comment by xiazhenhua** [comment]
> > [xlh001](https://github.com/xlh001) / [study_xxqg](https://github.com/xlh001/study_xxqg)这个可以正常使用
> 
> 可以正常使用，感谢

怎么跑起来的，  
cd study_xxqg
go mod tidy
go build ./
./study_xxqg     最后这个命令怎么用，跑不起来啊

**Comment by TSL-Johnson** [comment]
提供一个方法吧。
先将xlh001/study_xxqg拉取到服务器
cd study_xxqg
mkdir opt
cd opt
wget https://github.com/xlh001/study_xxqg/releases/download/2023.03.22-1144/study_xxqg_amd64
cd .
vim Dockerfile
将这一行COPY ./dist/docker_linux_$TARGETARCH*/study_xxqg /opt/study_xxqg改为COPY opt/study_xxqg /opt/study_xxqg
保存退出
docker build -t xlh001/study_xxqg/study_xxqg:latest .
docker run --name study_xxqg -d -p 8080:8080 -v /etc/study_xxqg/:/opt/config/  xlh001/study_xxqg:latest
你就拥有了它

**Comment by xlh001** [comment]
已修复，请更新。
