### ISSUE TITLE
对接公众号平台，提交配置成功，但是公众号没有菜单

### ISSUE THREAD

**Issue by dq1024** [sjkhsl/study_xxqg#24]
对接公众号平台，提交配置成功，但是公众号没有菜单。没有获取openid按钮，也没有登录之类的按钮。微信公众号那边显示配置成功。打开WX页面，显示no signtrue

**Comment by Nothend** [comment]
一样的问题，公众号没菜单，打开WX页面，显示no signtrue，其他步骤都正常通过
