### ISSUE TITLE
点了更新程序不会自动更新，版本号没变

### ISSUE THREAD

**Issue by gk34577** [sjkhsl/study_xxqg#25]
![Screenshot_20230401_092417_Samsung Internet](https://user-images.githubusercontent.com/75005427/229259057-276d4b6c-90c2-4535-8dc2-cf4f602a11ff.jpg)
![Screenshot_20230401_092406_Samsung Internet](https://user-images.githubusercontent.com/75005427/229259058-ad97afa6-b6eb-4b34-9db2-2d099be4fc81.jpg)

**Comment by smoryan** [comment]
你直接在release下载就行啦

**Comment by zniyuniyu** [comment]
下载后怎么操作

**Comment by zniyuniyu** [comment]
> release下载
