### ISSUE TITLE
群晖docker用一键安装报错 帮忙看看，菜鸟请教

### ISSUE THREAD

**Issue by bingbaicai** [sjkhsl/study_xxqg#26]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:61: mounting "/etc/study_xxqg" to rootfs at "/volume1/@docker/aufs/mnt/59c46d270215459f016ad314876d012f49dd8726a976aa7cb9e91ac4299c60e7/opt/config" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by qqqm7** [comment]
改改目录，别直接用，群晖不让

**Comment by qqqm7** [comment]
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:61: mounting "/etc/study_xxqg" to rootfs at "/volume1/@docker/aufs/mnt/59c46d270215459f016ad314876d012f49dd8726a976aa7cb9e91ac4299c60e7/opt/config" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

改改目录，别直接用，群晖不让
