### ISSUE TITLE
不进行每日答题，麻烦帮忙看看

### ISSUE THREAD

**Issue by des1pa2ir** [sjkhsl/study_xxqg#27]
![33446-effddbdbb3719afe0910bbb5771bb844](https://user-images.githubusercontent.com/129651422/230690033-053d1208-0170-4d4a-ab75-96012950ca60.jpg)
![347916-52a06e546dac640b5dc10b765d29b0ee](https://user-images.githubusercontent.com/129651422/230690069-48e38b2c-71a2-4d7b-bf31-863eb213f010.jpg)

**Comment by xlh001** [comment]
请联系相应项目人员进行处理，该镜像非本项目维护
