### ISSUE TITLE
运行后提示模块异常

### ISSUE THREAD

**Issue by cunyu52** [sjkhsl/study_xxqg#32]
Windows
试了半天都不行，是缺少什么环境吗
![微信截图_20230413102328](https://user-images.githubusercontent.com/71634417/231631418-3f69b9de-31f1-49ef-b59d-1f13149c90bf.png)

**Comment by xlh001** [comment]
重新拉以一下镜像看看

**Comment by cunyu52** [comment]
> 重新拉以一下镜像看看

重新试了1.0.40版本的可以了，谢谢
