### ISSUE TITLE
大佬，如何单独运行study_xxqg_windows_386.exe程序

### ISSUE THREAD

**Issue by coward0720** [sjkhsl/study_xxqg#37]
单独运行study_xxqg_windows_386程序时，按照配置文件修改config，再次运行提示：
![微信截图_20230517233114](https://github.com/sjkhsl/study_xxqg/assets/94579536/b2106437-7405-4ad3-a0ee-96cd00424aa6)
同时登录8080端口显示
![微信截图_20230517233129](https://github.com/sjkhsl/study_xxqg/assets/94579536/c4812aca-1726-4278-ab3d-05643d8c5b17)

本人是个菜鸟，大佬求教如何单文件运行study_xxqg_windows_386这个程序？

**Comment by coward0720** [comment]
经过大佬提示，目前已经能够调用浏览器接口，但在创建新用户时提示如下
![微信截图_20230524004316](https://github.com/sjkhsl/study_xxqg/assets/94579536/94895393-01c7-4980-8028-a2e82e4bb8fd)
然后我用苹果手机输入127.0.0.1:8080则提示无法链接服务器。请大佬明示

**Comment by as23751782** [comment]
IP地址不对，127.0.0.1是你手机的地址，你要输电脑的IP。不知道怎么看IP的话搜索“windwos查看ip”，跟着做就行了。然后手机上输入 电脑IP:8080

**Comment by coward0720** [comment]
> IP地址不对，127.0.0.1是你手机的地址，你要输电脑的IP。不知道怎么看IP的话搜索“windwos查看ip”，跟着做就行了。然后手机上输入 电脑IP:8080

谢谢这位大佬雪中送炭，终于搞定了，万分感谢
