### ISSUE TITLE
学习模块异常

### ISSUE THREAD

**Issue by coward0720** [sjkhsl/study_xxqg#40]
![微信截图_20230607085030](https://github.com/sjkhsl/study_xxqg/assets/94579536/58257259-9ff6-4f9d-acf9-7b4981a9e770)
自从这个东西更新了答题机制后，开始学习就自动这样了

**Comment by xlh001** [comment]
尝试修复，请重试。

**Comment by coward0720** [comment]
1.0.42版本下载使用，仍然提示各个模块异常

**Comment by xlh001** [comment]
尝试删除用户后重新添加看看
