### ISSUE TITLE
每日学习分数较低

### ISSUE THREAD

**Issue by africa1207** [sjkhsl/study_xxqg#53]
刷题模式选择的3，但是学习分数只有29，使用的docker，能否增加趣味答题
![image](https://github.com/sjkhsl/study_xxqg/assets/21698755/9308373e-f6f9-4a04-b546-96e4cb2a8bff)

**Comment by xlh001** [comment]
网页版已无趣味答题模块，无法添加，当前该项目只支持网页版上的功能
