### ISSUE TITLE
docker不能更新到最新版本。

### ISSUE THREAD

**Issue by lukemin** [sjkhsl/study_xxqg#59]
<html>
<body>
<div class="x-grid3-row x-grid3-row-selected x-grid3-row-over" role="row" id="ext-gen6026" style="margin: 0px; padding: 0px; cursor: default; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-color: rgb(220, 230, 240) rgb(220, 230, 240) rgba(198, 212, 224, 0.4); border-image: initial; width: 1319px; background-image: none; background-position: left top; background-size: initial; background-repeat: repeat-x; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgba(5, 127, 235, 0.1) !important; color: rgb(65, 75, 85); font-size: 13px; font-family: Verdana, Arial, &quot;Microsoft YaHei&quot;, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">

当前有更新的 study_xxqg 可供更新, 请前往 https://github.com/sjkhsl/study_xxqg/releases 下载. | stdout
-- | --

</div>
</body>
</html>
[2023-09-01 11:52:30] [info] 当前版本: v1.0.43-SNAPSHOT-67ad056 最新版本: v1.0.46

**Comment by xlh001** [comment]
直接重建容器
