### ISSUE TITLE
docker关闭cron后依然无法自动学习

### ISSUE THREAD

**Issue by no1ajian** [sjkhsl/study_xxqg#61]
推送方式只配置了ding，cron和cron random wait都关闭了，但容器启动后没有自动开始学习，需要手动点击开始学习，请问如何修改配置？谢谢！

**Comment by xlh001** [comment]
cron都关闭了，怎么会自动学习，用默认配置就好了，只要修改cron配置学习时间及推送方式即可
# 设置是否定时执行学习程序，格式为cron格式
# "9 19 * * *" 每天19点9分执行一次
# "0 10 * * *” 每天早上十点执行一次
