### ISSUE TITLE
登陆积分不正常

### ISSUE THREAD

**Issue by cvk792** [sjkhsl/study_xxqg#68]
已经开始学习，但登陆积分依旧是0/1，无法正确获取积分。手动打开强国app后，登陆积分可以正确获取，显示为1/1。
该问题可以用于判别使用工具作弊：学习积分时间早于登陆时间，即没登陆就能获取学习积分。
希望能尽快修复。

**Comment by klcb2010** [comment]
附议  的确有这个问题

**Comment by XiaoQiang67** [comment]
只能每天自己打开APP 一下，目前我就是这么解决的
