### ISSUE TITLE
 CentOS 7.9 报错

### ISSUE THREAD

**Issue by hellohankk** [sjkhsl/study_xxqg#70]
[2023-11-01 18:53:41] [31m[erro] [0m[core]  could not install driver: could not install driver: could not check if driver is up2date: could not run driver: exit status 134
[2023-11-01 18:53:41] [31m[erro] [0m[core] 安装playwright失败

**Comment by XiaoQiang67** [comment]
CentOS 7.9 不是 playwright-go 官方推荐环境，playwright安装应该是失败，playwright安装和安装依赖的脚本是apt-get命令的 (Debian、Ubuntu),因此CentOS 安装报错，会报告你依赖没安装。确保你的go环境是正常的，试试下面：

go env -w GOPROXY=https://goproxy.cn,direct
go env -w GOSUMDB=sum.golang.google.cn
sudo yum install libgnomeui-devel
go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps

如果还是不行，下载Playwright 1.20 version.[v0.2000.1](https://github.com/playwright-community/playwright-go/releases/tag/v0.2000.1)，把源代码上传到服务器并解压缩，进入到源代码的目录：
cd  cmd/playwright
go run main.go install --with-deps
然后你再运行 ./study_xxqg  看看终端里的提示，如果顺利下载了Chromium，那就没问题了。
我是想小白，自己百度的

**Comment by xlh001** [comment]
Linux系统建议通过docker进行部署
