### ISSUE TITLE
随即等待时间似乎没有起效

### ISSUE THREAD

**Issue by sampoon** [sjkhsl/study_xxqg#71]
感谢大神制作如此方便的软件，任务完成正常，但是随机等待时间似乎没有左右，下面是我的配置
# 设置是否定时执行学习程序，格式为cron格式
# "9 19 * * *" 每天19点9分执行一次
# "0 10 * * *” 每天早上十点执行一次
cron: "0 6,11,16 * * *"

# 定时任务随机等待时间，单位：分钟
cron_random_wait: 5

设置随机等待5分钟，但是每次开启任务时间似乎没有等待就开始了，请问如何使其生效呢？重启什么的都试过了

谢谢

**Comment by XiaoQiang67** [comment]
# 设置是否定时执行学习程序，格式为cron格式
cron: "0 */8 * * *"

# 定时任务随机等待时间，单位：分钟
cron_random_wait: 30

这是我的设置，如果随机等待时间短，有可能差1分钟，是不是没感觉出来？不妨多设定几分钟看看。

**Comment by sampoon** [comment]
是的设置为30等待，今天助手上线时间有延后了，谢谢
