### ISSUE TITLE
封号来了

### ISSUE THREAD

**Issue by klcb2010** [sjkhsl/study_xxqg#76]
第一次  11.20  缝了七天  今天早上通知封号 30天

**Comment by itltf512116** [comment]
咋操作的？我这边目前为止还算正常，只是需要在每天自动答题之前，先自己打开一次来APP来把登录积分完成了

**Comment by klcb2010** [comment]
``

> 咋操作的？我这边目前为止还算正常，只是需要在每天自动答题之前，先自己打开一次来APP来把登录积分完成了

不清楚他的逻辑  两个账号同时进行，我这个被封了 ，没有实名那个正常

**Comment by pili-book** [comment]
这程序需要每天登陆吗还是登录上很多天不用管

**Comment by klcb2010** [comment]
> 这程序需要每天登陆吗还是登录上很多天不用管

这个得看cookie有效期  一般来说  是永久 除非封号

**Comment by L1aohai** [comment]
老哥 能加个绿泡泡或者tg 教一教吗……实在弄不好

**Comment by L1aohai** [comment]
是真弄不好……就是docker运行的 但是添加账号那里 怎么用移动端打开？ 后续的一些我都还没到那一步 不知道还有些别的问题没有

**Comment by pili-book** [comment]
> docker运行 代码复制 粘贴就行了

微信公众号推送如何设置了，我打开那个网站token和网址都没有，我docker安装在威联通里，感觉实在闹不懂，呢么多参数有个教程没有

**Comment by klcb2010** [comment]
> > docker运行 代码复制 粘贴就行了
> 
> 微信公众号推送如何设置了，我打开那个网站token和网址都没有，我docker安装在威联通里，感觉实在闹不懂，呢么多参数有个教程没有

我设定的推送➕

**Comment by pili-book** [comment]
打开那个网站，不知道token是得自己建设吗？还得自己先架设一个服务器吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月8日(周一) 中午11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sjkhsl/study_xxqg] 封号来了 (Issue #76)




   
docker运行 代码复制 粘贴就行了
  
微信公众号推送如何设置了，我打开那个网站token和网址都没有，我docker安装在威联通里，感觉实在闹不懂，呢么多参数有个教程没有
  
我设定的推送➕

**Comment by klcb2010** [comment]
> 打开那个网站，不知道token是得自己建设吗？还得自己先架设一个服务器吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月8日(周一) 中午11:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sjkhsl/study_xxqg] 封号来了 (Issue #76) docker运行 代码复制 粘贴就行了 微信公众号推送如何设置了，我打开那个网站token和网址都没有，我docker安装在威联通里，感觉实在闹不懂，呢么多参数有个教程没有 我设定的推送➕ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

百度一下吧  基础的东西 😂
