### ISSUE TITLE
无法安装playwright是怎么回事啊

### ISSUE THREAD

**Issue by NightS13** [sjkhsl/study_xxqg#8]
win版本，显示无法从这个网页下载https://playwright.azureedge.net/builds/driver/next/playwright-go-1.20.0-beta-1647057403000-win32_x64.zip

**Comment by qa2286805252** [comment]
兄弟这个问题你解决没有  无法安装palywright

**Comment by zhouyuyu888** [comment]
应该是windows7 32位无法安装。
